name: CI/CD with Render

on:
  push:
    branches:
      - main  # Change this to your deployment branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: render/$GITHUB_REPOSITORY:latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Deploy to Render
      run: |
        render deploy --force
      env:
        RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}
